name: data_pipeline_lab
version: 1.0.0
config-version: 2

profile: data_pipeline_lab

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  data_pipeline_lab:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
